### PR TITLE
Gh1215 cookies samesite attr part2

### PR DESCRIPTION
**Pull request by joshrabinowitz**
Builds on gh1215_cookies_samesite_attr for #1215

### CODE REVIEW

**Comment by joshrabinowitz** [comment]
@bigpresh I moved forward with this PR. 
Can you help with docs and next steps?
Using this code and using `session_same_site: "Strict"` in `config.yml` didn't effect the cookie in my testing.

**Review by bigpresh — APPROVED** [review]
This looks sane; oddly I don't see the access_lines having 4 requests.  I think I'll tweak that test after merging this to just make sure that there is only one request logged - anything more than that is a fail, doesn't matter exactly how many.

**Comment by bigpresh** [comment]
You say it didn't affect the cookie in your testing?  The tests included confirm that it does add the option when requested to.

Anyway, I'll get this merged as it is, then tweak that access_logs test and add some doco etc.

**Comment by joshrabinowitz** [comment]
@bigpresh Maybe I'm configuring it wrong. 

Can you show an example of what a config file would look like that sets the `same_site` attribute? 

Also, it looks like configuring this attribute is not documented in this branch? If you show an example as above, I'll submit a doc patch.

**Comment by bigpresh** [comment]
Yeah, I need to add tests for the session setting (there's tests already for Dancer::Cookie behaving correctly depending on what samesite attribute it gets given), and document it.  I'll do that ASAP.

**Comment by bigpresh** [comment]
Right, doco on the new session_same_site setting added in 89f9ccf78c53d9cf27e237556c591e713e6433e5 and some tests for it in 0edd9529e254e9c4807ee152e106f672a862795f and a new trial release heading to CPAN.

**Comment by tangentsoft** [comment]
I've tested this change on my D1 app, and it seems to work. Can we get a release, please?

**Comment by bigpresh** [comment]
Yeah, it's about time this got out there.  I've been meaning to find time to investigate a few test failures on the test release: http://matrix.cpantesters.org/?dist=Dancer%201.3514-TRIAL

I'll try to find some time soon, work, children and home life permitting!

**Comment by knutov** [comment]
Only one non critical error about XML left, that test can be disabled, I think.

As for now it's possible to install new version this way:

```bash
PERL_CPANM_OPT=" --notest " cpanm Dancer@1.3514_03
```

**Pull request merged**
