### PR TITLE
Minimal travis-ci configuration

### PR DESCRIPTION
**Pull request by nunorc**
Add a mininal travis configuration to work with dzil. This should work.

### CODE REVIEW

**Comment by nunorc** [comment]
It seems something is missing in dzil config: Required plugin Dist::Zilla::Plugin::Test::ReportPrereqs isn't installed.

**Comment by bigpresh** [comment]
Hmm, on my box here, installation of Dist-Zilla-PluginBundle-YANICK (which contains a metric fuckton of stuff, I'm pretty sure it's not all required!) fails.

Probably need to figure out which plugins are actually required, rather than requiring a huge bundle.

**Comment by bigpresh** [comment]
After trying to install that bundle, though, it seems to have left dzil broken for me:

```
[davidp@supernova:~/dev/github/Dancer]$ dzil listdeps
Invalid version format (version required) at /usr/local/share/perl/5.14.2/Module/Runtime.pm line 386.
BEGIN failed--compilation aborted at /usr/local/share/perl/5.14.2/Dist/Zilla/Chrome/Term.pm line 4.
Compilation failed in require at /usr/local/share/perl/5.14.2/Dist/Zilla/App.pm line 97.
```

Getting closer and closer to  ditching dzil...

**Comment by nunorc** [comment]
It seems that Dist-Zilla-PluginBundle-YANICK requires Dist-Zilla-Plugin-Test-ReportPrereqs, but it does not have that requirement configured. Commit 607a2a12fcb1af9d91fd9e6c40c27e5a3924aca2 explicitly adds the required module.

Now looking at travis-ci build details the problem seems to be in Dist-Zilla-Plugin-ChangeStats-Git.

**Comment by nunorc** [comment]
Dist::Zilla::Plugin::ChangeStats::Git is failling. Since it seems to be used to output some details about the revision (nothing major), commit 48af67a8957943bb9e9c7b98396c87448a9dfcdf removes the plugin.

**Comment by bigpresh** [comment]
Hmm, appears to be getting as far as trying to run the tests using `dzil test` now, but outputs an error from Path::Tiny over and over, then dies:

```
34.99s$ dzil test
[DZ] building distribution under .build/_2IGEBfMml for installation
[DZ] beginning to build Dancer
[@Filter/NextVersion::Semantic] Bumping version from 1.3142 to 1.3143
[DZ] writing Dancer in .build/_2IGEBfMml
Unrecognized option(s) passed to make_path(): err at /home/travis/perl5/perlbrew/perls/5.16/lib/site_perl/5.16.3/Path/Tiny.pm line 1051.
Unrecognized option(s) passed to make_path(): err at /home/travis/perl5/perlbrew/perls/5.16/lib/site_perl/5.16.3/Path/Tiny.pm line 1051.
[...repeated lots...]
fatal: Not a valid object name undefined
The command "dzil test" exited with 128.
```

**Comment by bigpresh** [comment]
and annoyingly my main dev machine has some other interesting problem running `dzil test` which I'll probably have to poke about in the debuggerer to figure out:

```
[davidp@supernova:~/dev/github/Dancer]$ dzil authordeps
Invalid version format (version required) at /usr/local/share/perl/5.14.2/Module/Runtime.pm line 386.
BEGIN failed--compilation aborted at /usr/local/share/perl/5.14.2/Dist/Zilla/Chrome/Term.pm line 4.
Compilation failed in require at /usr/local/share/perl/5.14.2/Dist/Zilla/App.pm line 97.
```

**Comment by nunorc** [comment]
Commit f9b338e2f554572b510dad9271b6ff2b24c3dcaa adds Path-Tiny requirement to silent previous make_path warning.

**Comment by nunorc** [comment]
Sorry, can't reproduce the current travis-ci failure in my local setup, using same perl version, same distro, etc. Not sure where the problem is.

**Comment by bigpresh** [comment]
I meant to update this to say that I worked out the error I was getting from Module::Runtime on my dev box - ISTR upgrading Moose fixed it.

So far I can't reproduce the problem that Travis is seeing - doing what it does on my dev VM works fine.  Will see if I can figure it out, and maybe see if I can contact someone there for help - they may be able to grab a log file with more useful output or something.

**Comment by bigpresh** [comment]
In fact, "fatal: Not a valid object name undefined" sounds like a Git error to me...

**Comment by ambs** [comment]
This reminds me of a ticket where I ask @yanick to make dzil stuff easier to install by third party people. But unfortunately, the result was of little difference...

**Comment by bigpresh** [comment]
Closing this as PR #1132 (which is this PR checked out as a branch with additional changes then re-PR'd) appears to have cracked it.

**Comment by yanick** [comment]
On 2015-10-04 04:14 PM, Alberto Simões wrote:
> This reminds me of a ticket where I ask @yanick
> to make dzil stuff easier to install by
> third party people. But unfortunately, the result was of little
> difference...

Funny. @yanick remembers answering all questions that came @yanick's
way, tweaking the repo configuration when possible, telling you what was
the issue on your side when not. In fact @yanick remembers pointing out
what is probably the issue here in
https://github.com/PerlDancer/Dancer/issues/1109#issuecomment-101751768

Also, I'll repeat it for the record: you guys don't like the
dzil-powered system, that is fine -- you are now the maintainers and the
system should now be adapted to make your life easier. If you don't want
dzil, *ALL YOU NEED TO DO IS*

	$ git checkout devel
	$ git merge -s their master

and that's it, you're dzil-free.

**Comment by ambs** [comment]
Yes, @yanick, you did. Sorry if I sound harsh. Wasn't my point. But I confess that after you tweking the repo I continued having difficulties. Nevertheless, it seems it is fixed now :-)

**Comment by yanick** [comment]
On 2015-10-05 04:01 AM, Alberto Simões wrote:
> Yes, @yanick, you did. Sorry if I sound
> harsh. Wasn't my point. 

Then it wasn't expressed very well. There was no question. There was no
request. There was only a negative comment, with me being '@' to be sure
I'd get it. If not wanting to be harsh, what was the point of that
comment, then?

> But I confess that after you tweking the repo I
> continued having difficulties.

Well, did you follow-up with more questions? Because if not, I'm afraid
no-one is a mind-reader, and that's on you.

**Comment by ambs** [comment]
Well, I didn't say it was fixed either. So... :)

**Pull request closed without merging**
