### PR TITLE
Avoids constantly query session backend

### PR DESCRIPTION
**Pull request by tildedave**
So we are having a similar issue to https://github.com/PerlDancer/Dancer/issues/992 - large-ish project, Redis session backend, and it seems that every time we use `session 'foo'`, it does a Redis query to retrieve the value `'foo'` from the session.  This has gotten past the point of being cute as we are at the point of ~60 queries per page hit.  Our bad in not examining this earlier of course.

A better approach would be to store the session in request-local context using Dancer's `var`s so that the session backend query is only done once, and it is written out multiple times (if not lazy) or only once (if lazy). This matches my experience with how other session middleware works in frameworks like Python Django.  (On cursory examination Dancer2 also seems to behave this way.)

I'm a newbie to Dancer and not a great Perl programmer, so I'm not sure how much of this is right - and even if so, still some things to do here, so I'd appreciate feedback on the approach.  Thanks for looking!

### CODE REVIEW

**Comment by tildedave** [comment]
One issue I see with the code that's here - that I need feedback on - is that it doesn't properly handle `session->destroy`.

**Comment by racke** [comment]
I support that idea though I believe @xsawyerx will claim that we don't do any substantial development in Dancer 1 anymore. @shadowcat-mst isn't the big fan either or our session implementation as per IRC  discussion yesterday.

**Comment by xsawyerx** [comment]
Caching the session in a singleton sounds like... a problematic approach, at the very least. It also sounds like an indelicate change to a version that's meant to stay stable.

The great @yanick could decide whether to incorporate it or not.

Instead of continuing to patch a problematic implementation (with another possibly problematic implementation), I suggest trying out Dancer2.

**Comment by yanick** [comment]
I'll try to have a look at this in the upcoming days.

**Comment by yanick** [comment]
@tildedave I've pushed a fix to the devel branch. The resulting post-dzil code is in the 'build/devel' branch. Care to install it and see if it solves your problems in a satisfactory manner?

**Comment by tildedave** [comment]
Looks great!  I installed Dancer devel locally and I'm only seeing one GET query. Thank you for looking into this issue!

**Pull request closed without merging**
