### PR TITLE
Allow mixed named params and splats in route captures v2

### PR DESCRIPTION
**Pull request by bigpresh**
This is @veryrusty's PR 1086, checked out into a branch so I could tweak it and cherry-pick in a tweak to our Travis config so I can see it tested on the new Travis infratstructure.

### CODE REVIEW

**Comment by bigpresh** [comment]
Merged in devel branch to get up to date and see if Travis gives it a green light - tests pass fine for me locally with these changes.

**Comment by veryrusty** [comment]
Thanks @bigpresh !

**Comment by bigpresh** [comment]
Unfortunately some CPAN Testers runs failed, in a way that I *think* is related to these changes, but I'm not yet certain.

For example:

```
t/03_route_handler/15_prefix.t ...................... ok

#   Failed test 'Only 9 paths'
#   at t/03_route_handler/16_caching.t line 152.
#          got: 8
#     expected: 9

#   Failed test 'Correct paths'
#   at t/03_route_handler/16_caching.t line 158.
#     Structures begin differing at:
#          $got->[0][1] = '/54362.286173161628.282223772610686391.470510827822980.169335028864704.118268305813938.25357580337045.928226132226620.483840294553624.243059909314045.58022059135689.927032050488693.52734343835943.269534720632323.36013733923296.612635045761479.558164464143116.90413701718056.097689842752954.247268246861996.0381624902'
#     $expected->[0][1] = '/47465.04361691921657.3319224338981577.53830251686926.900039929863002.972373852789912.039188372877362.628578341376967.511891736858944.11792314255670.314208822661273.370549239945834.608081622119414.709005089689024.82920265821979.759045527882340.754609332277369.096226543935793.667075066963912.7889501242'
# Looks like you failed 2 tests of 66.
t/03_route_handler/16_caching.t ..................... 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/66 subtests 
```

Some of the reports:
http://www.cpantesters.org/cpan/report/d8334646-7fba-11e5-aab2-8e65cfe82091
http://www.cpantesters.org/cpan/report/af010b0c-7d15-11e5-ae39-7a72cfe82091
http://www.cpantesters.org/cpan/report/017ff5ca-7dd2-11e5-916f-bfdb5feaeb47
http://www.cpantesters.org/cpan/report/8cb4b316-8006-11e5-aab2-8e65cfe82091

I haven't yet had a chance to figure out what's going on - it doesn't happen for me, though.

**Comment by bigpresh** [comment]
Unable to reproduce that test failure myself on 5.20.2, which would seem to rule out hash key randomisation as a cause, which is what I suspected it might have been.  Looks like this requires further investigation.

**Comment by bigpresh** [comment]
I hope I've fixed this, in PR-1137.  Looks like it was nothing to do with the changes in this PR, as similar CPAN Testers failure reports existed for Dancer releases before this PR was merged.

**Pull request merged**
